-- MySQL Script generated by MySQL Workbench
-- Thu Nov 27 09:46:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rapido_seguro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rapido_seguro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rapido_seguro` DEFAULT CHARACTER SET utf8 ;
USE `rapido_seguro` ;

-- -----------------------------------------------------
-- Table `rapido_seguro`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_seguro`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_seguro`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_seguro`.`telefones` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `telefone` CHAR(11) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_telefone`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  INDEX `fk_telefones_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapido_seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_seguro`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_seguro`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` CHAR(8) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_enderecos_clientes_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapido_seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_seguro`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_seguro`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `tipo_entrega` VARCHAR(45) NOT NULL,
  `distancia` DECIMAL(10,2) NOT NULL,
  `peso_carga` DECIMAL(10,2) NOT NULL,
  `valor_base_km` DECIMAL(10,2) NOT NULL,
  `valor_base_kg` DECIMAL(10,2) NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_endereco` INT NOT NULL,

  PRIMARY KEY (`id_pedido`),

  INDEX `fk_pedidos_clientes_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_pedidos_enderecos_idx` (`id_endereco` ASC) VISIBLE,

  CONSTRAINT `fk_pedidos_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapido_seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,

  CONSTRAINT `fk_pedidos_enderecos`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `rapido_seguro`.`enderecos` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_seguro`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_seguro`.`entregas` (
  `id_pedido_entrega` INT NOT NULL,
  `valor_distancia` DECIMAL(10,2) NOT NULL,
  `valor_peso` DECIMAL(10,2) NOT NULL,
  `acrescimo` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL,
  `taxa_extra` DECIMAL(10,2) NOT NULL,
  `valor_final` DECIMAL(10,2) NOT NULL,
  `status_entrega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pedido_entrega`),
  CONSTRAINT `fk_entregas_pedidos1`
    FOREIGN KEY (`id_pedido_entrega`)
    REFERENCES `rapido_seguro`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;